trip/urls.py
from django.contrib import admin
from django.urls import path,include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.controller')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]

myapp/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models

# Create your models here.

#Blog model
from django.urls import reverse
from star_ratings.models import Rating


class Post(models.Model):
    loc=models.CharField(max_length=50,help_text="Enter Place name")
    city = models.CharField(max_length=50, help_text="Enter city name")
    desc=models.CharField(max_length=500,help_text="Enter Description")
    price=models.IntegerField(help_text="Enter Booking Price")
    img = models.CharField(max_length=100, help_text='add url of image')
    show=models.BooleanField(help_text="Enter 0 if post is private")

    def __str__(self):
        # passing value at time of post objcet calling
        return '{}{}'.format(self.loc, self.price)

    def get_absolute_url(self):
        return reverse('myapp:home')

class Rate(models.Model):
    ratings=GenericRelation(Rating, related_query_name='foos')
    s_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    u_id=models.ForeignKey(User,on_delete=models.CASCADE)

myapp/controller.py
from django.urls import path
from .views import home,detailPost,book, signuppage, signout, Addplace, loginpage

app_name='myapp'
urlpatterns = [
    path('', home,name='home'),
    path('post/<slug:id>/', detailPost, name='detailPost'),
    path('book/', book, name='book'),
    path('login/',loginpage,name='login'),
    path('signup/',signuppage,name='signup'),
    path('logout/',signout,name='logout'),
    path('addplace/',Addplace.as_view(),name='addplace'),


]

myapp/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic import CreateView

from .myforms import Login, Register
from .models import Post
# Create your views here.

def home(request):
    a = Post.objects.all()
    user = False
    try:
        myid = int(request.session.get('user'))
        user = User.objects.get(id=myid)
        if user.is_authenticated:
            pass
        else:
            user = False

    except:
        pass
    return render(request, 'myapp/home.html', {'val': a,'user':user})

def detailPost(request,id):
   # a=Album.objects.get(id=id)
   a=Post.objects.filter(city__contains=id)
   user = False
   try:
       myid = int(request.session.get('user'))
       user = User.objects.get(id=myid)
       if user.is_authenticated:
           pass
       else:
           user = False
   except:
       pass
   return render(request,'myapp/detailPost.html',{'val':a,'user':user})

def book(request):

    return render(request, 'myapp/book.html')

def loginpage(request):
    print('hello')
    form=Login(request.POST or None)
    if form.is_valid():
        val=request.GET.get('next')
        u=form.cleaned_data.get('Username')
        p=form.cleaned_data.get('Password')
        val2=authenticate(username=u,password=p)
        request.session['user'] = val2.id
        print(val2)
        login(request,val2)
        if val:
            return redirect(val)
        else:
            return redirect('myapp:home')
    return render(request,'myapp/login.html',{'form':form,'user':False})

def signout(request):
    try:
        del(request.session['user'])
    except:
        pass
    logout(request)
    return redirect('myapp:home')

def signuppage(request):
    form= Register(request.POST or None)
    if form.is_valid():
        data=form.save(commit=False)
        p=form.cleaned_data.get('password')
        data.set_password(p)
        data.save()
        return redirect('/login')
    return render(request,'myapp/login.html',{'form':form,'user':False})

class Addplace(LoginRequiredMixin,CreateView):
    template_name = 'myapp/login.html'
    model = Post
    login_url='myapp:login'
    fields=['loc','city','desc','price','img','show']
    context_object_name = 'form'

myapp/templates/myapp/book.html
{% extends 'myapp/master.html' %}
{% block title %}book{% endblock %}

{% block main %}

    <img src=" https://previews.123rf.com/images/farakos/farakos1506/farakos150600005/
    41967693-yellow-under-construction-sign-and-three-orange-traffic-cones-isolated-on-white-background.jpg"
         align="middle"; style=width:60%; >


{% endblock %}

myapp/templates/myapp/detailPost.html
{% extends 'myapp/master.html' %}

{% block title %}home{% endblock %}
{% block main %}
    <div class="row">
        {%for i in val %}
  <div class="col-sm-3">
    <div class="thumbnail">
      <img src="{{ i.img }} " width="500" height="200" alt="No Image Found">
      <div class="caption">
          <h4><bold>{{i.city }}</bold></h4>
        <h3>{{i.loc}}</h3>
        <p>{{i.desc}}</p>
         <p>Rs&nbsp{{i.price}}</p>

        <p><a href='{% url 'myapp:book' %}' class="btn btn-primary" role="button">Book</a>
         <a href='{% url "myapp:home" %}' class= "btn btn-default" role="button">Home</a>
          </p>

         </div>

    </div>
  </div>
    {% endfor %}
</div>




{% endblock %}

myapp/templates/myapp/home.html
{% extends 'myapp/master.html' %}
{% load ratings %}
{% block title %}home{% endblock %}
{% block main %}
    <div class="col-xs-8">
    <div class="row">
        {%for i in val %}
  <div class="col-sm-3 " >
    <div class="thumbnail" style="width: 200px;height: 400px">
      <img src="{{ i.img }} " width="500" height="200" alt="No Image Found">

      <div class="caption">
        <h4><bold>{{i.city }}</bold></h4>
        <h3>{{i.loc}}</h3>
        <p>{{i.desc}}</p>
        <h3>Rs&nbsp{{i.price}}</h3>
       <p><a href={% url 'myapp:book' %} class="btn btn-primary" role="button">Book</a>
          <a href='{% url 'myapp:detailPost' i.city%}' class="btn btn-default" role="button">More Places</a>
        </p>

      </div>
    </div>
  </div>
    {% endfor %}
</div>

    </div>


{% endblock %}

myapp/templates/myapp/login.html
{% extends 'myapp/master.html' %}
{% block title %} login{% endblock %}

{% block main %}

    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
    </form>
{% endblock %}

myapp/templates/myapp/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-light" style="background-color: black">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" style="background-color: Tomato" ><span class="icon-bar" > Trip</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href={% url 'myapp:home' %}>  <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home <span class="sr-only">(current)</span></a></li>
        <li><a href={% url 'myapp:addplace' %}><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Place</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" action="http://google.com/search" target="_blank">
        <div class="form-group"action="/" method="post">
          <input type="text" class="form-control" placeholder="Search" name ="q">

        </div>
        <button type="submit" class="btn btn-default" value="Search">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

          {% if not user %}
              <li><a href="{% url 'myapp:signup' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Signup</a></li>
        <li><a href="{% url 'myapp:login' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Login</a></li>

          {% else %}

              <li> <h4 style="color: chartreuse">Hi, {{ user.username }}</h4>  </li>
          <li><a href="{% url 'myapp:logout' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Logout</a></li>

          {% endif %}

       </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block main%}{% endblock %}
</body>
</html>